# Generated by Django 4.2.15 on 2024-09-28 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='seconds',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='title',
        ),
        migrations.RemoveField(
            model_name='timers',
            name='uuid',
        ),
        migrations.AddField(
            model_name='timers',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timers',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timers',
            name='time_completed',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
