# Generated by Django 4.2.15 on 2024-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0005_event_completion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blocking_events',
            field=models.ManyToManyField(blank=True, related_name='blocked_events', to='pomo.event'),
        ),
    ]
