# Generated by Django 4.2.15 on 2024-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0006_event_blocking_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstate',
            name='completed_events',
            field=models.ManyToManyField(blank=True, null=True, to='pomo.event'),
        ),
    ]
