# Generated by Django 4.2.15 on 2024-10-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0007_alter_playerstate_completed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
