# Generated by Django 4.2.15 on 2024-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0009_achievement_reward_balance_achievementcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
