# Generated by Django 4.2.15 on 2025-01-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomo', '0014_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='size',
            field=models.IntegerField(default=15000),
        ),
        migrations.CreateModel(
            name='PartnerQuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=15000)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partner_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField(default=15000)),
                ('partner1_progress', models.IntegerField(default=0)),
                ('partner2_progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner1', to=settings.AUTH_USER_MODEL)),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
