# Generated by Django 4.2.15 on 2025-01-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0015_friendrequest_size_partnerquestrequest_partnerquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='size',
        ),
    ]
