# Generated by Django 4.2.15 on 2025-01-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0018_alter_event_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('outcome_type', models.CharField(choices=[('add_points', 'Add Points')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='events_with_outcome', to='pomo.eventoutcome'),
        ),
    ]
