# Generated by Django 4.2.15 on 2025-01-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0019_eventoutcome_event_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
