# Generated by Django 4.2.15 on 2025-01-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0020_playerstate_current_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='highest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
