# Generated by Django 4.2.15 on 2025-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo', '0023_alter_playerquestprogress_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquestprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
