# Generated by Django 4.2.15 on 2024-08-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_tracker', '0003_alter_dailyprogress_cites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='cites',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='equations',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='figures',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='inlines',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
