# Generated by Django 4.2.15 on 2024-08-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_tracker', '0005_alter_dailyprogress_cites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogress',
            name='cites',
        ),
    ]
